### ISSUE TITLE
js errors in console

### ISSUE THREAD

**Issue by mostly-harmless** [smartinsightsfromdata/rpivotTable#11]
rpivotTable seems to work fine. However, any idea how I might get rid of the errors in the js console (chrome) with rpivotTable in Shiny? Does an addresourceadd need to be added perhaps? This is using Shiny 0.11.1

![screen shot 2015-02-11 at 10 48 44 am](https://cloud.githubusercontent.com/assets/2998956/6153749/ba3bbf4a-b1db-11e4-998d-172d2711b8e7.png)

**Comment by smartinsightsfromdata** [comment]
@mostly-harmless let me try...

**Comment by smartinsightsfromdata** [comment]
@mostly-harmless Interesting: I do not have them (apart the favicon error - which shouldn't be a problem)

![screen shot 2015-02-11 at 19 02 11](https://cloud.githubusercontent.com/assets/3786727/6154029/a687d3b8-b220-11e4-9b49-fd820b9a3480.png)

**Comment by mostly-harmless** [comment]
FYI happens locally as well



—

Vincent R. Nijs

Associate Professor of Marketing

Rady School of Management

University of California, San Diego

Wells Fargo Hall, 3W116

9500 Gilman Drive # 0553 | La Jolla, CA  920930553

858.822.7459 ǀ vnijs@ucsd.edu

**Comment by smartinsightsfromdata** [comment]
I tried also on shinyapps and again I get only the favicon error.  My screen is small (I'm on the road) and I cannot see it, but the error counter is definitely at 1...

![screen shot 2015-02-11 at 19 07 32](https://cloud.githubusercontent.com/assets/3786727/6154162/7d7e5d9c-b221-11e4-8155-afb1cfb2a0c7.png)

**Comment by smartinsightsfromdata** [comment]
Not sure if it is a red herring, but it is interesting that you get the error because the browser is not able to locate the  source maps for the libraries.  I am using the canary 64 bits build of chrome (apparently the right one for js development - I'm told).  In reality they are not necessary and it could be an option in certain environments.
Try to look [here](https://developer.chrome.com/devtools/docs/javascript-debugging#source-maps) for source maps. I'll try to see if I can test vanilla chrome.

**Comment by smartinsightsfromdata** [comment]
@mostly-harmless Well even a freshly downloaded chrome does not give these errors (even the favicon one disappears...).  I am not sure what to suggest.  I have submitted minor changes to github (mainly about testing and other minors) and I haven't touched the yaml. But maybe you could try to re-install the library?  (just because I'm running out of options...)

![screen shot 2015-02-11 at 19 29 50](https://cloud.githubusercontent.com/assets/3786727/6154616/ed810808-b224-11e4-99b8-1922f5244665.png)

**Comment by smartinsightsfromdata** [comment]
@mostly-harmless this so post seems quite straightforward - [here](http://stackoverflow.com/questions/18365315/jquerys-jquery-1-10-2-min-map-is-triggering-a-404-not-found)
The question remains why you have the error and I don't?
I've also tried to re-install rpivotTable with the same result (i.e. no errors).

**Comment by smartinsightsfromdata** [comment]
@mostly-harmless could you kindly confirm that chrome has the devtool setting "Enable JavaScript source maps" enabled? I suspect it is harmless (pun!) if you set it in any case...

**Comment by mostly-harmless** [comment]
I will try that this afternoon. Thanks for looking into this Enzo!



—

Vincent R. Nijs

Associate Professor of Marketing

Rady School of Management

University of California, San Diego

Wells Fargo Hall, 3W116

9500 Gilman Drive # 0553 | La Jolla, CA  920930553

858.822.7459 ǀ vnijs@ucsd.edu

**Comment by mostly-harmless** [comment]
I turned ‘enable js source maps’ off and no more error. Thanks



—

Vincent R. Nijs

Associate Professor of Marketing

Rady School of Management

University of California, San Diego

Wells Fargo Hall, 3W116

9500 Gilman Drive # 0553 | La Jolla, CA  920930553

858.822.7459 ǀ vnijs@ucsd.edu

**Comment by smartinsightsfromdata** [comment]
@mostly-harmless I am glad it worked, but I still cannot explain why I  could load them with no errors (on plain chrome & canary) and you couldn't....
