### ISSUE TITLE
drag-and-drop stopped working with latest htmlwidgets, shiny, etc.

### ISSUE THREAD

**Issue by vnijs** [smartinsightsfromdata/rpivotTable#18]
See https://github.com/rstudio/DT/issues/22 (last comment)

**Comment by yihui** [comment]
I don't know where the breakage came from. This minimal example still works fine:

```r
library(shiny)
library(rpivotTable)
shinyApp(
  ui = fluidPage(rpivotTableOutput('foo')),
  server = function(input, output) {
    output$foo = renderRpivotTable({
      rpivotTable(mtcars)
    })
  }
)
```

I'm afraid it will be a little difficult to debug your specific app due to its scale https://vnijs.shinyapps.io/marketing/ The error in the JavaScript console seems to indicate that there were issues with jQueryUI. FWIW, shiny uses a tailored version of jQueryUI 1.10.4 and this package uses 1.9.4: https://github.com/smartinsightsfromdata/rpivotTable/blob/master/inst/htmlwidgets/lib/jqueryui/jquery-ui.min.js I'm not sure if that could be the problem.

Since the error message is not clear enough. I guess you will have to reduce the number of elements in the UI and try to isolate the problem as much as you can.

**Comment by vnijs** [comment]
Your example does indeed still work. I will see what I can find out and will check with @smartinsightsfromdata

**Comment by smartinsightsfromdata** [comment]
@vnijs   I've just tested the shiny example (Canadian election) that goes with the package and works fine.
I have:
- shiny 0.11.1.9004
- rpivotTable 0.1.3.4 (and the last changes I made were largely cosmetic)
- jsonlite 0.9.16
- htmlwidget 0.3.3

As my wrapper basically pass the data to the pivottable, it looks like a possible conflict due to jQueryUI.
I have used the same libraries used by Nicolas (pivottable author) on his github page. The jquery-ui version is 1.9.2. (but I found a buglet in rpivotTable yaml: it was wrongly labelled as 1.11.2).
Nicolas recently had this to say about dependencies etc. https://github.com/nicolaskruchten/pivottable/issues/309
```
The examples have all been tested and all work with jQuery 1.8.3 and jQueryUI 1.9.2. 
It's a good bet that later versions will work well, and it's kind of a crapshoot if you want to use later versions.
```
Because of the above I prefer to keep rpivottable aligned to Nicolas' libraries.

I will do the following (in the next few minutes):
- correct yaml file and push the version as 0.1.3.5
- create a jquery-ui-1.10.4 branch and post it (I just tested it and appear to work - but I haven't tested it in all context)
Let me know if I you would like me to add other changes to this branch (namely a different jquery version).
Please note that d3 and c3 are "unchangeable" and aligned.

**Comment by vnijs** [comment]
It seems there was also a version of jquery-ui in Radiant. Once removed everything works fine. Sorry to waste your time

**Comment by smartinsightsfromdata** [comment]
@vnijs no problem!

**Comment by vnijs** [comment]
Nice of you to say that Enzo

**Comment by yihui** [comment]
Thanks @smartinsightsfromdata. As I said, I'm a little worried about the jQuery UI library included in shiny, because currently it has excluded the slider component (https://github.com/rstudio/shiny/issues/799). But if you use a higher version than shiny's jQuery UI, htmlwidgets will choose your version.
