### ISSUE TITLE
issue with htmlwidgets & shiny server

### ISSUE THREAD

**Issue by YvesCR** [smartinsightsfromdata/rpivotTable#24]
I am trying to run a shiny app including a rpivottable.

my config: devtools 1.8.0, htmlwidgets 0.4.2, rpivotTable 0.1.4.1, shiny 0.12.0

R version 3.1.2 (2014-10-31)

Ubuntu 14.04.1 LTS

My code works perfectly locally, but on the server it crash and I get this error on the console:
TypeError: x is undefined

And it links to this code:

HTMLWidgets.widget({

    name: 'rpivotTable',

    type: 'output',

    initialize: function(el, width, height) {

        return {}

    },

    renderValue: function(el, x, instance) {
        x.data = HTMLWidgets.dataframeToD3(x.data);

        var derivers = $.pivotUtilities.derivers;
      var tpl = $.pivotUtilities.aggregatorTemplates;

      x.params.renderers = $.extend(
        $.pivotUtilities.renderers,
        $.pivotUtilities.d3_renderers,
        $.pivotUtilities.c3_renderers
      );

      $('#'+el.id).pivotUI(
            x.data, x.params
      );

    },

    resize: function(el, width, height, instance) {

    }

});

My R code is the following:

if (interactive()) {  lib.path <- my.path.local
} else {  lib.path <- my.path.server }

### packages ###
library(shiny, lib.loc =  lib.path)
library(htmlwidgets, lib.loc = lib.path)
library(rpivotTable, lib.loc = lib.path)

data <- data.frame(var1 = c("mod1", "mod2"), value = c(1, 2))

shinyApp(
  ui =  fluidPage(
    sidebarLayout(
      sidebarPanel(
    textOutput("config"),  textOutput("path"), textOutput("version"))
    , mainPanel(
     rpivotTableOutput("test")
    )
    )), 

  server = function(input, output) {
       output$test <- rpivotTable::renderRpivotTable({
         rpivotTable(data = data)
       })

    output$config <- renderText({ 
      tt <- installed.packages()
     paste(paste(tt[tt[, 1] %in% c("shiny", "htmlwidgets", "rpivotTable", "devtools") , 1], 
                tt[tt[, 1] %in% c("shiny", "htmlwidgets", "rpivotTable", "devtools") , 3]), collapse = ", ")
    })

    output$path <- renderText({ 
      ll <- .libPaths()
      ll
    })

    output$version <- renderText({ 
      ss <- sessionInfo()
      ss[[1]]$version.string
    })

  }
)

does anybody already met this error?

best,

**Comment by smartinsightsfromdata** [comment]
@YvesCR I'm perplexed.  I've run your code on my macbook pro without problems.  I do get the "usual" error about missing favIcon.  See https://github.com/rstudio/shiny/issues/833. The "usual" way to eliminate the issue is to have a ```www``` folder with a ```favIcon.ico```. 

Could you kindly:
- paste your ```sessionInfo()``` after you  had the error
- paste the exact JS error from the error console

By the way, htmlwidgets needs to be downloaded, but it is attached directly by rpivotTable (as any other htmlwidgets package) and does not need to be explicitly loaded.

On the other hand I am a bit concerned by the fact that you seem to "force" the usage of different libraries (I wonder what is your use case and what is different).  
Among other things you need to make sure that you have all the proper packages / versions in both libraries.  Moreover, if you alternate between libraries within the same session, you should be sure that you detach all the packages of the library you do not want to use, forcing the unload of the relative ```namespace``` as well, e.g. using (for all relevant packages):
```R
detach("package:rpivotTable", unload=TRUE)
```
Incidentally, if you have "save workspace on exit" set to TRUE, just restarting R will not be enough: you will continue to load the "old" packages each time...

Please see below my ```sessioninfo()``` output.  The differences in R version (or the use of a shiny version directly from github) should not warrant an error, but it would be better to compare it against your ```sessionInfo()```.

```R
> sessionInfo()
R version 3.2.0 Patched (2015-05-01 r68301)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rpivotTable_0.1.4.1 htmlwidgets_0.4.2   shiny_0.12.0.9002  

loaded via a namespace (and not attached):
 [1] R6_2.0.1         rsconnect_0.3.77 htmltools_0.2.6  tools_3.2.0      rstudioapi_0.3.1
 [6] yaml_2.1.13      Rcpp_0.11.6      jsonlite_0.9.16  digest_0.6.8     xtable_1.7-4    
[11] httpuv_1.3.2     mime_0.3   
```

**Comment by YvesCR** [comment]
Hi,

sorry to bothered you.

I am using AWS and upgraded the instance from t2.micro to t2.small and it solved the issue :)

Probably it comes from the size of the RAM.

best,
