### ISSUE TITLE
isolate the variable drag-and-drop

### ISSUE THREAD

**Issue by mostly-harmless** [smartinsightsfromdata/rpivotTable#3]
Nice binding!

Question: Is it possible to use the variable drag-and-drop functionality without the tables/graphs etc.? R could then handle the plotting, summarizing, etc.

**Comment by smartinsightsfromdata** [comment]
Thanks @mostly-harmless! 

While pivottable has three renderers as default (standard; D3 and GoogleChart - more can be custom developed in JS), my implementation has only the standard renderer. 

The reason is that the heat map offered by the D3 renderer didn't look particularly exciting, and as far as GoogleChart, my apps must be able to work also without an internet connection.  Sadly GoogleChart t&c do not allow the storing of the library in absence of a connection and I found this too limiting.

Moreover currently all the features of the standard renderers are fully driven from R: it is possible to launch the pivottable with pre-defined settings for rows, cols etc.

The way I envisage to use this library in R is mainly in conjunction with shiny apps, using R and shiny (plus any additional htmlwidgets libraries etc.) to build feature-rich, advanced visualisations / UIs.

**Comment by smartinsightsfromdata** [comment]
@mostly-harmless please let me know if I can close this issue.
