### ISSUE TITLE
conflict with ggiraph ?

### ISSUE THREAD

**Issue by brunelserge** [smartinsightsfromdata/rpivotTable#65]
hello

when im using rpivotable and [ggiraph](https://github.com/davidgohel/ggiraph) in a same markdown or shiny app rpivotable graph (ex: barchart) aren't working
it say : An error occurred rendering the PivotTable results. (table and  heatmap are working)

i put a md inside .zip just put the ggiraph part in comment and it's working again

[conflict.zip](https://github.com/smartinsightsfromdata/rpivotTable/files/701016/conflict.zip)

**Comment by smartinsightsfromdata** [comment]
We've had similar issues in the past.  Unfortunately they are usually due to incompatible version of some of the libraries (usually jquery) specified in each package, e.g. ggiraph and rpivotTable, loaded by htmlwidgets.

Sadly it is difficult to come up with a permanent resolution (e.g. the fix for one would cause problems to others): we are awaiting to see if something is forthcoming withhtmlwidgets.

A possible (horrible!) fix would be to fork one of the two libraries, and change the jquery version in `rpivotTable/inst/htmlwidgets/lib/` and in the yaml file: at the moment is the best suggestion I can offer.
But please feel free to research the issue:   I would like for somebody to propose a brilliant solution!
